version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.5.2
    volumes:
      - dbdata:/data/db 
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  dbdata: