package com.tf.yana.DataUpload;

public interface Constants {

	String DBURL = "DBURL";
	String DBUSERNAME = "DBUSERNAME";
	String DBPASSWORD = "DBPASSWORD";
	String DBSCHEMA_NAME = "DBSCHEMA_NAME";
	String ESURL = "ESURL";
	String AUTHORIZATION = "AUTHORIZATION";
	String JDBC_DRIVER_LIBRARY = "jdbc_driver_library";
	
	String CONNECTION_STRING_REPLACE = "<CONNECTION_STRING>";
	String SCHEMA_NAME_REPLACE = "<SCHEMA_NAME>";
	
	String DB_USER_NAME_REPLACE = "<DB_USER_NAME>";
	String DB_PASSWORD_REPLACE = "<DB_PASSWORD>";
	
	String JDBC_DRIVER_LIBRARY_REPLACE = "<jdbc_driver_library>";
	
	String ESURL_REPLACE = "<ES_URL>";
	String AUTHORIZATION_REPLACE = "<AUTHORIZATION>";
	String LOCAL_ES_URL = "LOCAL_ES_URL";
	String LOCAL_ES_URL_REPLACE = "<LOCAL_ES_URL>";
}
